name: cosee_lints
description: Lint rules and metrics for Dart and Flutter used internally at cosee GmbH.
repository: https://github.com/cosee/cosee_lints
homepage: https://pub.dev/publishers/cosee.biz/packages
issue_tracker: https://github.com/cosee/cosee_lints/issues
version: 0.11.0
topics:
  - lints

environment:
  sdk: ^3.9.0
