blank_issues_enabled: false
contact_links:
  - name: Request help
    url: https://github.com/cosee/cosee_lints/discussions/categories/request-help
    about: Need assistance or guidance with the cosee_lints package? We're here to help!
