name: cosee_lints

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Cache dart dependencies
        uses: actions/cache@v6
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-dart-${{ hashFiles('example/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-dart-
      - name: Install Dependencies
        run: |
          dart pub get
          echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"
          dart pub global activate pana
      - name: Verify Pub Score
        run: ./tool/verify_pub_score.sh
